CREATE TABLE Drugs
(
  id SERIAL UNIQUE PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  m_date DATE NOT NULL,
  exp_date TIMESTAMP NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE Users
(
  id SERIAL UNIQUE PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  address VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  created_on TIMESTAMP
);

CREATE TABLE MedRecords
(
  id SERIAL UNIQUE PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  patient_id INT REFERENCES Patients(id) NOT NULL,
  created_on TIMESTAMP NOT NULL
);

CREATE TABLE Patients
(
  id SERIAL UNIQUE NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  address VARCHAR(255) NOT NULL,
  age INTEGER,
  sex VARCHAR(255) NOT NULL,
  dob TIMESTAMP NOT NULL,
  created_on TIMESTAMP NOT NULL
);

CREATE TABLE Prescriptions
(
  id SERIAL UNIQUE NOT NULL PRIMARY KEY,
  duration VARCHAR(255) NOT NULL,
  no_of_times_per_day INT NOT NULL,
  patient_id INT REFERENCES Patients(id) NOT NULL,
  drug_id INT REFERENCES Drugs(id) NOT NULL,
  time_for_prescription VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
